[input]
html_selector = "main"
base_directory = "output"

[[input.files]]
path = "pages/about-me.html"
url = "/pages/about-me.html"
title = "About me"

[[input.files]]
path = "how-does-android-implement-compose-jetpack.html"
url = "/how-does-android-implement-compose-jetpack.html"
title = "How does Android implement Compose Jetpack"

[[input.files]]
path = "overview-of-coroutines.html"
url = "/overview-of-coroutines.html"
title = "OverView of Coroutines"

[[input.files]]
path = "crisp-dm-series-mastering-data-mining-in-football-analytics.html"
url = "/crisp-dm-series-mastering-data-mining-in-football-analytics.html"
title = "CRISP-DM Series: Mastering Data Mining in Football Analytics"

[[input.files]]
path = "streamlining-api-integration-with-kiota.html"
url = "/streamlining-api-integration-with-kiota.html"
title = "Streamlining API Integration with Kiota"

[[input.files]]
path = "tacotron-2-for-persian-language.html"
url = "/tacotron-2-for-persian-language.html"
title = "Tacotron 2 For Persian language"

[[input.files]]
path = "bag-of-words-example.html"
url = "/bag-of-words-example.html"
title = "Bag of Words Example"

[[input.files]]
path = "logistic-regression-example.html"
url = "/logistic-regression-example.html"
title = "Logistic Regression Example"

[[input.files]]
path = "k-means-clustering-example.html"
url = "/k-means-clustering-example.html"
title = "K-Means Clustering Example"
